/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles.index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as ServicesRequestsRouteImport } from './routes/services.requests'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RequestsBrowseRouteImport } from './routes/requests.browse'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as OfficialPostsIdRouteImport } from './routes/official-posts.$id'
import { Route as GuidesPropertyMaintenanceKampalaRouteImport } from './routes/guides.property-maintenance-kampala'
import { Route as BusinessesNewRouteImport } from './routes/businesses.new'
import { Route as BusinessesCreateRouteImport } from './routes/businesses.create'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedListSkillRouteImport } from './routes/_authenticated/list-skill'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests.new'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests.$id'
import { Route as AuthenticatedProfilesNewRouteImport } from './routes/_authenticated/profiles.new'
import { Route as AuthenticatedProfilesIdRouteImport } from './routes/_authenticated/profiles.$id'
import { Route as AuthenticatedNotificationsPreferencesRouteImport } from './routes/_authenticated/notifications.preferences'
import { Route as AuthenticatedNotificationsIdRouteImport } from './routes/_authenticated/notifications.$id'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessesRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRequestsRoute = ServicesRequestsRouteImport.update({
  id: '/services/requests',
  path: '/services/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsBrowseRoute = RequestsBrowseRouteImport.update({
  id: '/requests/browse',
  path: '/requests/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OfficialPostsIdRoute = OfficialPostsIdRouteImport.update({
  id: '/official-posts/$id',
  path: '/official-posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPropertyMaintenanceKampalaRoute =
  GuidesPropertyMaintenanceKampalaRouteImport.update({
    id: '/guides/property-maintenance-kampala',
    path: '/guides/property-maintenance-kampala',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessesNewRoute = BusinessesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BusinessesRoute,
} as any)
const BusinessesCreateRoute = BusinessesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BusinessesRoute,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessesRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListSkillRoute = AuthenticatedListSkillRouteImport.update({
  id: '/list-skill',
  path: '/list-skill',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesNewRoute =
  AuthenticatedProfilesNewRouteImport.update({
    id: '/profiles/new',
    path: '/profiles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilesIdRoute = AuthenticatedProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsPreferencesRoute =
  AuthenticatedNotificationsPreferencesRouteImport.update({
    id: '/notifications/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIdRoute =
  AuthenticatedNotificationsIdRouteImport.update({
    id: '/notifications/$id',
    path: '/notifications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/official': typeof OfficialRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-skill': typeof AuthenticatedListSkillRoute
  '/me': typeof AuthenticatedMeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/create': typeof BusinessesCreateRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/guides/property-maintenance-kampala': typeof GuidesPropertyMaintenanceKampalaRoute
  '/official-posts/$id': typeof OfficialPostsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/p/$slug': typeof PSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/requests/browse': typeof RequestsBrowseRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/u/$id': typeof UIdRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/profiles/$id': typeof AuthenticatedProfilesIdRoute
  '/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/official': typeof OfficialRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-skill': typeof AuthenticatedListSkillRoute
  '/me': typeof AuthenticatedMeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/create': typeof BusinessesCreateRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/guides/property-maintenance-kampala': typeof GuidesPropertyMaintenanceKampalaRoute
  '/official-posts/$id': typeof OfficialPostsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/p/$slug': typeof PSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/requests/browse': typeof RequestsBrowseRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/u/$id': typeof UIdRoute
  '/businesses': typeof BusinessesIndexRoute
  '/profiles': typeof ProfilesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/profiles/$id': typeof AuthenticatedProfilesIdRoute
  '/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/official': typeof OfficialRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/list-skill': typeof AuthenticatedListSkillRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/create': typeof BusinessesCreateRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/guides/property-maintenance-kampala': typeof GuidesPropertyMaintenanceKampalaRoute
  '/official-posts/$id': typeof OfficialPostsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/p/$slug': typeof PSlugRoute
  '/posts/$id': typeof PostsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/requests/browse': typeof RequestsBrowseRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/u/$id': typeof UIdRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/_authenticated/notifications/preferences': typeof AuthenticatedNotificationsPreferencesRoute
  '/_authenticated/profiles/$id': typeof AuthenticatedProfilesIdRoute
  '/_authenticated/profiles/new': typeof AuthenticatedProfilesNewRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/businesses'
    | '/contact'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/official'
    | '/opportunities'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/admin'
    | '/credits'
    | '/dashboard'
    | '/list-skill'
    | '/me'
    | '/settings'
    | '/welcome'
    | '/businesses/$slug'
    | '/businesses/create'
    | '/businesses/new'
    | '/guides/property-maintenance-kampala'
    | '/official-posts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/p/$slug'
    | '/posts/$id'
    | '/providers/$id'
    | '/requests/browse'
    | '/services/$slug'
    | '/services/requests'
    | '/u/$id'
    | '/businesses/'
    | '/profiles/'
    | '/services/'
    | '/messages/$id'
    | '/notifications/$id'
    | '/notifications/preferences'
    | '/profiles/$id'
    | '/profiles/new'
    | '/requests/$id'
    | '/requests/new'
    | '/messages/'
    | '/notifications/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/official'
    | '/opportunities'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/admin'
    | '/credits'
    | '/dashboard'
    | '/list-skill'
    | '/me'
    | '/settings'
    | '/welcome'
    | '/businesses/$slug'
    | '/businesses/create'
    | '/businesses/new'
    | '/guides/property-maintenance-kampala'
    | '/official-posts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/p/$slug'
    | '/posts/$id'
    | '/providers/$id'
    | '/requests/browse'
    | '/services/$slug'
    | '/services/requests'
    | '/u/$id'
    | '/businesses'
    | '/profiles'
    | '/services'
    | '/messages/$id'
    | '/notifications/$id'
    | '/notifications/preferences'
    | '/profiles/$id'
    | '/profiles/new'
    | '/requests/$id'
    | '/requests/new'
    | '/messages'
    | '/notifications'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/businesses'
    | '/contact'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/official'
    | '/opportunities'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/_authenticated/admin'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/list-skill'
    | '/_authenticated/me'
    | '/_authenticated/settings'
    | '/_authenticated/welcome'
    | '/businesses/$slug'
    | '/businesses/create'
    | '/businesses/new'
    | '/guides/property-maintenance-kampala'
    | '/official-posts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/p/$slug'
    | '/posts/$id'
    | '/providers/$id'
    | '/requests/browse'
    | '/services/$slug'
    | '/services/requests'
    | '/u/$id'
    | '/businesses/'
    | '/profiles/'
    | '/services/'
    | '/_authenticated/messages/$id'
    | '/_authenticated/notifications/$id'
    | '/_authenticated/notifications/preferences'
    | '/_authenticated/profiles/$id'
    | '/_authenticated/profiles/new'
    | '/_authenticated/requests/$id'
    | '/_authenticated/requests/new'
    | '/_authenticated/messages/'
    | '/_authenticated/notifications/'
    | '/_authenticated/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OfficialRoute: typeof OfficialRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  GuidesPropertyMaintenanceKampalaRoute: typeof GuidesPropertyMaintenanceKampalaRoute
  OfficialPostsIdRoute: typeof OfficialPostsIdRoute
  PSlugRoute: typeof PSlugRoute
  PostsIdRoute: typeof PostsIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  RequestsBrowseRoute: typeof RequestsBrowseRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesRequestsRoute: typeof ServicesRequestsRoute
  UIdRoute: typeof UIdRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/requests': {
      id: '/services/requests'
      path: '/services/requests'
      fullPath: '/services/requests'
      preLoaderRoute: typeof ServicesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/browse': {
      id: '/requests/browse'
      path: '/requests/browse'
      fullPath: '/requests/browse'
      preLoaderRoute: typeof RequestsBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/official-posts/$id': {
      id: '/official-posts/$id'
      path: '/official-posts/$id'
      fullPath: '/official-posts/$id'
      preLoaderRoute: typeof OfficialPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/property-maintenance-kampala': {
      id: '/guides/property-maintenance-kampala'
      path: '/guides/property-maintenance-kampala'
      fullPath: '/guides/property-maintenance-kampala'
      preLoaderRoute: typeof GuidesPropertyMaintenanceKampalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/new': {
      id: '/businesses/new'
      path: '/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof BusinessesNewRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/businesses/create': {
      id: '/businesses/create'
      path: '/create'
      fullPath: '/businesses/create'
      preLoaderRoute: typeof BusinessesCreateRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/list-skill': {
      id: '/_authenticated/list-skill'
      path: '/list-skill'
      fullPath: '/list-skill'
      preLoaderRoute: typeof AuthenticatedListSkillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/new': {
      id: '/_authenticated/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof AuthenticatedProfilesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles/$id': {
      id: '/_authenticated/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof AuthenticatedProfilesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/preferences': {
      id: '/_authenticated/notifications/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof AuthenticatedNotificationsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/$id': {
      id: '/_authenticated/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AuthenticatedNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedListSkillRoute: typeof AuthenticatedListSkillRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedNotificationsIdRoute: typeof AuthenticatedNotificationsIdRoute
  AuthenticatedNotificationsPreferencesRoute: typeof AuthenticatedNotificationsPreferencesRoute
  AuthenticatedProfilesIdRoute: typeof AuthenticatedProfilesIdRoute
  AuthenticatedProfilesNewRoute: typeof AuthenticatedProfilesNewRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedListSkillRoute: AuthenticatedListSkillRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedNotificationsIdRoute: AuthenticatedNotificationsIdRoute,
  AuthenticatedNotificationsPreferencesRoute:
    AuthenticatedNotificationsPreferencesRoute,
  AuthenticatedProfilesIdRoute: AuthenticatedProfilesIdRoute,
  AuthenticatedProfilesNewRoute: AuthenticatedProfilesNewRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BusinessesRouteChildren {
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  BusinessesCreateRoute: typeof BusinessesCreateRoute
  BusinessesNewRoute: typeof BusinessesNewRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesSlugRoute: BusinessesSlugRoute,
  BusinessesCreateRoute: BusinessesCreateRoute,
  BusinessesNewRoute: BusinessesNewRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  ContactRoute: ContactRoute,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OfficialRoute: OfficialRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  GuidesPropertyMaintenanceKampalaRoute: GuidesPropertyMaintenanceKampalaRoute,
  OfficialPostsIdRoute: OfficialPostsIdRoute,
  PSlugRoute: PSlugRoute,
  PostsIdRoute: PostsIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  RequestsBrowseRoute: RequestsBrowseRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesRequestsRoute: ServicesRequestsRoute,
  UIdRoute: UIdRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
