/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as ServicesRequestsRouteImport } from './routes/services.requests'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsBrowseRouteImport } from './routes/requests.browse'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as OpportunitiesNewRouteImport } from './routes/opportunities.new'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as OfficialPostsIdRouteImport } from './routes/official-posts.$id'
import { Route as BusinessesNewRouteImport } from './routes/businesses.new'
import { Route as BusinessesCreateRouteImport } from './routes/businesses.create'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessesRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRequestsRoute = ServicesRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsBrowseRoute = RequestsBrowseRouteImport.update({
  id: '/requests/browse',
  path: '/requests/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesNewRoute = OpportunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const OfficialPostsIdRoute = OfficialPostsIdRouteImport.update({
  id: '/official-posts/$id',
  path: '/official-posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesNewRoute = BusinessesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BusinessesRoute,
} as any)
const BusinessesCreateRoute = BusinessesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BusinessesRoute,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/official': typeof OfficialRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/create': typeof BusinessesCreateRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/official-posts/$id': typeof OfficialPostsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/browse': typeof RequestsBrowseRoute
  '/requests/new': typeof RequestsNewRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/u/$id': typeof UIdRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/official': typeof OfficialRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/create': typeof BusinessesCreateRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/official-posts/$id': typeof OfficialPostsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/browse': typeof RequestsBrowseRoute
  '/requests/new': typeof RequestsNewRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/u/$id': typeof UIdRoute
  '/businesses': typeof BusinessesIndexRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/official': typeof OfficialRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/create': typeof BusinessesCreateRoute
  '/businesses/new': typeof BusinessesNewRoute
  '/official-posts/$id': typeof OfficialPostsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/opportunities/new': typeof OpportunitiesNewRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/browse': typeof RequestsBrowseRoute
  '/requests/new': typeof RequestsNewRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/u/$id': typeof UIdRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/businesses'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/me'
    | '/notifications'
    | '/official'
    | '/opportunities'
    | '/services'
    | '/terms'
    | '/businesses/$slug'
    | '/businesses/create'
    | '/businesses/new'
    | '/official-posts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/providers/$id'
    | '/requests/$id'
    | '/requests/browse'
    | '/requests/new'
    | '/services/$slug'
    | '/services/requests'
    | '/u/$id'
    | '/businesses/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/me'
    | '/notifications'
    | '/official'
    | '/opportunities'
    | '/services'
    | '/terms'
    | '/businesses/$slug'
    | '/businesses/create'
    | '/businesses/new'
    | '/official-posts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/providers/$id'
    | '/requests/$id'
    | '/requests/browse'
    | '/requests/new'
    | '/services/$slug'
    | '/services/requests'
    | '/u/$id'
    | '/businesses'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/businesses'
    | '/contact'
    | '/credits'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/me'
    | '/notifications'
    | '/official'
    | '/opportunities'
    | '/services'
    | '/terms'
    | '/businesses/$slug'
    | '/businesses/create'
    | '/businesses/new'
    | '/official-posts/$id'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/providers/$id'
    | '/requests/$id'
    | '/requests/browse'
    | '/requests/new'
    | '/services/$slug'
    | '/services/requests'
    | '/u/$id'
    | '/businesses/'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  OfficialRoute: typeof OfficialRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  OfficialPostsIdRoute: typeof OfficialPostsIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsBrowseRoute: typeof RequestsBrowseRoute
  RequestsNewRoute: typeof RequestsNewRoute
  UIdRoute: typeof UIdRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/requests': {
      id: '/services/requests'
      path: '/requests'
      fullPath: '/services/requests'
      preLoaderRoute: typeof ServicesRequestsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/browse': {
      id: '/requests/browse'
      path: '/requests/browse'
      fullPath: '/requests/browse'
      preLoaderRoute: typeof RequestsBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/new': {
      id: '/opportunities/new'
      path: '/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof OpportunitiesNewRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/official-posts/$id': {
      id: '/official-posts/$id'
      path: '/official-posts/$id'
      fullPath: '/official-posts/$id'
      preLoaderRoute: typeof OfficialPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/new': {
      id: '/businesses/new'
      path: '/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof BusinessesNewRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/businesses/create': {
      id: '/businesses/create'
      path: '/create'
      fullPath: '/businesses/create'
      preLoaderRoute: typeof BusinessesCreateRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof BusinessesRoute
    }
  }
}

interface BusinessesRouteChildren {
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  BusinessesCreateRoute: typeof BusinessesCreateRoute
  BusinessesNewRoute: typeof BusinessesNewRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesSlugRoute: BusinessesSlugRoute,
  BusinessesCreateRoute: BusinessesCreateRoute,
  BusinessesNewRoute: BusinessesNewRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OpportunitiesNewRoute: typeof OpportunitiesNewRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OpportunitiesNewRoute: OpportunitiesNewRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesRequestsRoute: typeof ServicesRequestsRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesRequestsRoute: ServicesRequestsRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  ContactRoute: ContactRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  OfficialRoute: OfficialRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  OfficialPostsIdRoute: OfficialPostsIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsBrowseRoute: RequestsBrowseRoute,
  RequestsNewRoute: RequestsNewRoute,
  UIdRoute: UIdRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
