export const COUNTRY_CODES = [
  { name: "Uganda", code: "+256", flag: "🇺🇬", length: 9 },
  { name: "Kenya", code: "+254", flag: "🇰🇪", length: 9 },
  { name: "Tanzania", code: "+255", flag: "🇹🇿", length: 9 },
  { name: "Rwanda", code: "+250", flag: "🇷🇼", length: 9 },
  { name: "Burundi", code: "+257", flag: "🇧🇮", length: 8 },
  { name: "South Sudan", code: "+211", flag: "🇸🇸", length: 9 },
  { name: "Democratic Republic of the Congo", code: "+243", flag: "🇨🇩", length: 9 },
  { name: "United States", code: "+1", flag: "🇺🇸", length: 10 },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧", length: 10 },
  { name: "Canada", code: "+1", flag: "🇨🇦", length: 10 },
  { name: "Australia", code: "+61", flag: "🇦🇺", length: 9 },
  { name: "India", code: "+91", flag: "🇮🇳", length: 10 },
  { name: "South Africa", code: "+27", flag: "🇿🇦", length: 9 },
  { name: "Nigeria", code: "+234", flag: "🇳🇬", length: 10 },
  { name: "Ghana", code: "+233", flag: "🇬🇭", length: 9 },
  { name: "Egypt", code: "+20", flag: "🇪🇬", length: 10 },
  { name: "Morocco", code: "+212", flag: "🇲🇦", length: 9 },
  { name: "Ethiopia", code: "+251", flag: "🇪🇹", length: 9 },
  { name: "Zambia", code: "+260", flag: "🇿🇲", length: 9 },
  { name: "Zimbabwe", code: "+263", flag: "🇿🇼", length: 9 },
  { name: "Malawi", code: "+265", flag: "🇲🇼", length: 9 },
  { name: "Somalia", code: "+252", flag: "🇸🇴", length: 8 },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪", length: 9 },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦", length: 9 },
  { name: "China", code: "+86", flag: "🇨🇳", length: 11 },
  { name: "Japan", code: "+81", flag: "🇯🇵", length: 10 },
  { name: "Germany", code: "+49", flag: "🇩🇪", length: 10 },
  { name: "France", code: "+33", flag: "🇫🇷", length: 9 },
  { name: "Italy", code: "+39", flag: "🇮🇹", length: 10 },
  { name: "Brazil", code: "+55", flag: "🇧🇷", length: 11 },
  { name: "Mexico", code: "+52", flag: "🇲🇽", length: 10 },
  { name: "Argentina", code: "+54", flag: "🇦🇷", length: 10 },
];
